package main

var questions = []string{
	"Would you rather lose all your money or lose your best friend?",
	"Would you rather be a supervillain or a superhero?",
	"Would you rather never see your friend as a human or never see them at all?",
	"Would you rather live at any point in past of your choosing or live in the present?",
	"Would you rather be able to talk to animals or be able to speak any language?",
	"Would you rather never eat meat again or have to eat a main-course sized portion of meat with every meal for the rest of your life?",
	"Would you rather spend 10 years in prison or 20 years on a deserted island (you have access to everything you need for survival but cannot communicate with the outside world)?",
	"Would you rather have the ability to speak with dogs or cats?",
	"Would you rather be a famous comedian or a famous writer?",
	"Would you rather only be able to walk or only be able to jump (your endurance is the same in both situations)?",
	"Would you rather lose your ability to distinguish between fictional and non-fictional works BUT you can perform photosynthesis and don't have to eat, or continue life as is?",
	"Would you rather lose your ability to distinguish between fictional and non-fictional works BUT you no longer require sleep, or continue life as is?",
	"Would you rather Get $2000 a day for the rest of your life BUT you don't have the intuition to independently differentiate between nonfictional and fictional works or continue with life as is?",
	"Would you rather have the ability to read minds or communicate with others via telepathy (they can also communicate with you, but only when you want for them to be able to)?",
	"Would you rather only be able to eat fish or steak for the rest of your life? You have access to no other meat and cost is not a factor.",
	"Would you rather be able to fly at 10 miles per hour or be able to run at 50 miles per hour? Neither have any effect on your endurance",
	"Would you rather have your favorite NFL team win the superbowl or get $100?",
	"Would you rather never be able to use a knife again or never be able to use a fork again?",
	"Would you rather have to speak every thought you have out loud or have to start screaming uncontrollably for 5 seconds any time you see dairy products (happens at max once per minute)?",
	"Would you rather be a famous Twitch streamer or the star of your own (successful) sitcom?",
	"Would you rather be an extremely famous musician or an extremely famous pro-athlete? You are famous for the same period of time either way.",
	"Would you rather go on vacation to the mountains or to the beach?",
	"Would you rather become a chess grandmaster or an elite professional darts player? Your fame and net worth are the same either way.",
	"If given the choice of not showering for a week or not brushing your teeth for a week, what would you choose?",
	"Would you rather get a paper cut every time you read a book or never be allowed to pick up a book ever again?",
	"Would you rather have everything you eat be overcooked or raw (you will not get sick/suffer health-related consequences either way)?",
	"Would you rather have to sing the chorus to \"Friday\" by Rebecca Black every time you see or hear someone cough (for one week a month) or have every song you listen to be Friday by Rebecca Black (for two weeks a month)",
	"Would you rather have legs as long as your fingers or fingers as long as your legs?",
	"Would you rather be able to eat whatever you want (or nothing at all) and have it be perfectly healthy/optimal for your needs or never have to wait in traffic or any sort of line ever again?",
	"Would you rather always have the hiccups or always feel like you have to sneeze (you sneeze at the same frequency as you normally do)?",
	"Would you rather be a strawberry but have human thoughts (ie what you think of now) or be a human but only have strawberry thoughts (need sunlight, etc)?",
	"Would you rather have 1 billion dollars or have a random superpower that you don't get to choose? If you chose the second option, go to https://bit.ly/2WdtWda for your power",
	"Would you rather get 5 million dollars or get 1 million ducks you can telepathically control (you cannot sell the ducks)?",
	"Would you rather eat an oreo-sized spider (can be cooked) or eat 200 oreos (5lbs)? Both must be done uninterrupted in one sitting.",
	"Would you rather have the ability to teleport a total of 20 miles every 4 hours or never have to perform any kind of household chores again (laundry, dishes, etc)?",
	"Would you rather go back in time and assume the body of your 8 year old self with all the knowledge you have now or get $40 million in cash right now?",
	"Would you rather have unlimited quantities of any footlong sub for which you get to choose the ingredients or have unlimited quantities of any pizza for which you get to choose the toppings? Your ingredients/toppings are final once decided and no alterations can be made to either the pizza or footlong.",
	"Would you rather be the best athlete in the world at a MINOR sport (handball, volleyball, squash, etc) or be able to predict relatively inconsequential events you CANNOT bet on with perfect accuracy (weather, sporting events, whether a flight will be delayed, etc)?",
	"Would you rather have to say YOUU the same way Soulja Boy does in \"Crank That\" or have every song you listen to feature Soulja Boy instead of the original artist (ie, every song you listen to becomes a Soulja Boy cover of it)?",
	"Would you rather receive $10 every time you compliment someone or receive $500 every time you insult someone in the meanest way you can come up with?",
	"Would you rather have to watch Paul Blart: Mall Cop every time you wish to leave your home (time is frozen, so you're not wasting time, but you must sit through the whole movie without doing anything else) or lose your sense of smell?",
	"Would you rather receive $10 million in cash or get a Gulfstream G7 private jet, flown and maintained for free (you incur no cost despite how much you use the plane)?",
	"Would you rather have the ability to increase the height at which you jump by 4% every time you eat a standard bottle of ketchup (415ml) or have the ability to move furniture with your mind, but ONLY furniture you can see in front of you?",
}
