package main

var questions = []string{
	"Would you rather lose all your money or lose your best friend?",
	"Would you rather make a million dollars or make a rocket?",
	"Would you rather spend time with your family or spend time with friends?",
	"Would you rather be a villain or a hero?",
	"Would you rather hate your dream job or have a dream job and never get paid?",
	"Would you rather never see your friend as a human or never see them at all?",
	"Would you rather live in the past or live in the present?",
	"Would you rather live where it's always dark or always light?",
	"Would you rather go to the aquarium or go to the zoo?",
	"Would you rather go to the moon or go to Mars?",
	"Would you rather eat candy for the rest of your life or cheeseburgers?",
	"Would you rather eat ice cream or pizza in the morning?",
	"Would you rather live the same day for the rest of your life or live for only one day?",
	"Would you rather be able to talk to animals or be able to speak any language?",
	"Would you rather be able to talk your way out of trouble or fight your way out of trouble?",
	"Would you rather never be able to shower again or never be able to clip your toenails again?",
	"Would you rather be the last person in the world or be the best athlete in the world?",
	"Would you rather live in a world without problems or a world without poverty?",
	"Would you rather let your crush know you love them or hide your love for the rest of your life?",
	"Would you rather live in this same year for the rest of your life or live for one year in the future?",
	"Would you rather have free internet or have free coffee?",
	"Would you rather have free food or have free alcohol?",
	"Would you rather have too many warts or too many ulcers?",
	"Would you rather never be able to smell or never be able to fart?",
	"Would you rather never be able to see or never be able to hear?",
	"Would you rather go to an amusement park or go to the woods?",
	"Would you rather eat every meal with ketchup or vinegar?",
	"Would you rather be made publicly foolish or made publicly untrustworthy?",
	"Would you rather be able to speak French or Spanish?",
	"Would you rather eat meat for the rest of your life or eat vegetables?",
	"Would you rather spend 10 years in prison or 20 years on a deserted island?",
	"Would you rather have the ability to speak with dolphins or whales?",
	"Would you rather be the funniest person your friends know or the most trustworthy?",
	"Would you rather be a famous comedian or a famous writer?",
	"Would you rather lose the ability to speak or lose the ability to use your hands?",
	"Would you rather only be able to walk or only be able to jump?",
	"Would you rather date someone blind or date someone deaf?",
	"Would you rather lose your ability to read or lose your ability to eat?",
	"Would you rather have the ability to read minds or the ability to do sign language?",
	"Would you rather spend 10 years on an island or in the woods?",
	"Would you rather only be able to eat fish or steak for the rest of your life?",
	"Would you rather be able to fly or be able to hunt?",
	"Would you rather work in a nail salon or hair salon?",
	"Would you rather work for your dad or work for your mom?",
	"Would you rather spend a year with your sister or a year with your mom?",
	"Would you rather be good to others or have others be good to you?",
	"Would you rather have an easy time meeting friends or an easy time meeting boyfriends?",
	"Would you rather lose a sports match or lose a boyfriend?",
	"Would you rather die alone or die with your spouse?",
	"Would you rather eat food with a straw or eat food with a knife?",
	"Would you rather have your friend disown you or have your family know all your secrets?",
	"Would you rather eat alone for the rest of your life or always be hungry?",
	"Would you rather never meet your parents or spend years in prison?",
	"Would you rather never be able to clip your toenails or never be able to put on deodorant?",
	"Would you rather always burp when you see someone or always fart?",
	"Would you rather go out to dinner or go to a concert?",
	"Would you rather spend time together or go to an event?",
	"Would you rather always say everything on your mind or never speak again?",
	"Would you rather believe everything you're told or have the ability to lie?",
	"Would you rather have everything you do live-streamed or have a television show?",
	"Would you rather be stripped of everything you own or fall terminally ill with cancer?",
	"Would you rather go on vacation to Mexico or go to Iceland?",
	"Would you rather go on a bike ride or go for a walk?",
	"Would you rather date a guy every day for life or date an elephant for life?",
	"Would you rather be Instagram famous or movie star famous?",
	"Would you rather read books for the rest of your life or watch movies?",
	"Would you rather lose a close friend or lose a close family member?",
	"Would you rather have two dogs or two cats?",
	"Would you rather never marry or never have kids?",
	"Would you rather live a year in Paris or a year in Italy?",
	"Would you rather have a job that paid well or work for a great boss?",
	"Would you rather have tons of free time or have no friends?",
	"Would you rather eat a rat or eat a mouse?",
	"Would you rather be able to run really fast or jump really high?",
	"Would you rather go surfing or go snowboarding?",
	"Would you rather go to the mountains or go to the beach?",
	"Would you rather a girl text you or call you on the phone?",
	"Would you rather live in a tiny apartment in the city or a house in the middle of nowhere?",
	"Would You Rather be always slightly hot or slightly cold?",
	"What would you choose if you had the option of chewing cold, hard ice cream or eating hot, steaming food without blowing it?",
	"Would you rather become a chess grandmaster or an elite kickboxer?",
	"If given the choice of not showering for a week or not brushing your teeth for a week, what would you choose?",
	"Would you rather get a paper cut every time you read a book or never be allowed to pick up a book ever again?",
	"Which one would you choose: the superhuman ability to read minds or having all of your lies believed?",
	"Would you rather eat only fried food or eat only boiled food for the rest of your life?",
	"Which would you rather be— a great boss but a terrible human being or a bad boss but a great human being?",
	"Would you rather lose the ability to cry or cry at least once a day for the rest of your life?",
}
